version: '3.8'

services:
  wedding-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=REDACTED # http://www.leonard-stocks.com/api/admin/predictions?password=REDACTED&format=csv
      - SITE_PASSWORD=REDACTED # http://www.leonard-stocks.com/api/auth/qr-login?token=REDACTED
    volumes:
      - ./uploads:/app/public/uploads
      - ./data:/app/data  # Add this line!
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 10G
          cpus: '1.0'